### ISSUE TITLE
React SCSS implement

### ISSUE THREAD

**Issue by bluetch** [bluetch/shopee_design#1]
I used to write SCSS instead of CSS, but don't know how to install, I am a beginner of React, please kindly help me, thank you.

My expect: when run "npm start", it can also sync SCSS to CSS let me live review it, and run build also available SCSS to CSS.

**Comment by jhondelbaguio** [comment]
Let me help you.

**Comment by bdbch** [comment]
@bluetch I'll send you a Pullrequest with a webpack implementation so you can just watch the SCSS files.

**Comment by bluetch** [comment]
Thanks for jhondelbaguio help!
