### ISSUE TITLE
sidebar active miss [React][JavaScript]

### ISSUE THREAD

**Issue by bluetch** [bluetch/shopee_design#11]
active style should follow when users click for each link, but now only can change by group, could anyone help me check it?

File: /src/module/sidebar.js

**Comment by Jeffrey-Chang** [comment]
@bluetch I can work on this

**Comment by lazycoder9** [comment]
I'll take it

**Comment by lazycoder9** [comment]
@Jeffrey-Chang sorry buddy) I've already made PR)
But there is 2 solutions:
1) Change PureComponent to Component
2) Change shouldComponentUpdate on Submenu
I preferred second one

**Comment by Jeffrey-Chang** [comment]
@lazycoder9 No problem :)

**Comment by bluetch** [comment]
thank you guys, but there are still error, when second click another group, it really hard for me...

**Comment by lazycoder9** [comment]
@bluetch made another PR, this time fixed this by passing location as props to child components
https://github.com/bluetch/shopee_design/pull/15

**Comment by bluetch** [comment]
@lazycoder9 cool, thank you! :)
