### ISSUE TITLE
layouts error HTML or CSS problem

### ISSUE THREAD

**Issue by bluetch** [bluetch/shopee_design#12]
In index page (Home.js), there are 3 articles catch from Medium, but the third layout's formatting is off, and one more title should not appear. It should be HTML problem, but I am hard to find out, please help me.

![screenshot 2017-10-07 15 40 06](https://user-images.githubusercontent.com/4100698/31305854-ddec4b30-ab75-11e7-9b58-26b95e1a9937.png)

**Comment by gigobyte** [comment]
I can look into it.

**Comment by bluetch** [comment]
Great! thank you @gigobyte ! Really helpful!
