### ISSUE TITLE
Sass mixin fail to use

### ISSUE THREAD

**Issue by bluetch** [bluetch/shopee_design#4]
There are hints when I finish my SCSS, but it fail to compile mixin, how could I do it? use sass-resources-loader?

`//Instead of the line below you could use @include transition($transition-1, $transition-2, $transition-3, $transition-4, $transition-5, $transition-6, $transition-7, $transition-8, $transition-9, $transition-10)
	transition: opacity 0.15s ease-in-out;`

**Comment by sgangadhar02** [comment]
You can do it this way by below mixin property: 

`@mixin transition($transition-property, $transition-time, $method) {
  -webkit-transition: $transition-property $transition-time $method;
  -moz-transition: $transition-property $transition-time $method;
  -ms-transition: $transition-property $transition-time $method;
  -o-transition: $transition-property $transition-time $method;
  transition: $transition-property $transition-time $method;
}`

**Comment by bluetch** [comment]
@sgangadhar02 thank you. I would like to know is there something like resource library to add all of them it?

**Comment by sgangadhar02** [comment]
@bluetch : No library needed. Just create one mixin.scss file and add the mixin property. And then use it wherever you want.

**Comment by bluetch** [comment]
@sgangadhar02 but there are lots hint to be fix, eg: @include box-shadow, @include border-radius, @include box-sizing, @include transition
