### ISSUE TITLE
Update React to v15

### ISSUE THREAD

**Issue by arthurdenner** [bluetch/shopee_design#5]
In the other repository, you wanted to update the project, rewriting the app in the current version of React... Do you still want to do this? I believe I can help.

Note: Since the project is using `react-router: v2.0.0` and other packages that are incompatible with `React v16`, we can't jump to `React v16` directly. We need to move to `React v15` first, update other packages to version compatibles with `React v16` and then move to it.

What do you think, @bluetch? I can take care of this.

**Comment by bluetch** [comment]
Hi @arthurdenner ,
Is it hard to do it? I afraid spend you much time, if possible, I would like to do it.

**Comment by arthurdenner** [comment]
No, it is not that hard. I already started, tomorrow I'll send you the PR.

**Comment by bluetch** [comment]
@arthurdenner Cool, its great for me, thank you!!

**Comment by arthurdenner** [comment]
Hi, @bluetch. Could you tell me why this issue was reopened?

**Comment by bluetch** [comment]
Hi @arthurdenner , its just remind me have to upgrade v16 :)

**Comment by arthurdenner** [comment]
Got it. But I think would be better open another issue to that, since you'll need to update other packages before jumping to React v16.

**Comment by bluetch** [comment]
understand that, thank you @arthurdenner
