### ISSUE TITLE
SCSS mixin fail, don't know how to implement sass-resources-loader

### ISSUE THREAD

**Issue by bluetch** [bluetch/shopee_design#7]
SCSS mixin fail, don't know how to implement sass-resources-loader
Could someone help me?

**Comment by Martskin** [comment]
@bluetch I just created a PR with some suggested SCSS refactoring. https://github.com/bluetch/shopee_design/pull/10

**Comment by jhondelbaguio** [comment]
@bluetch : I created a PR based on your request. But i highly suggest to refactor the SCSS as @Martskin suggestion.

**Comment by bluetch** [comment]
thank you @Martskin, I merge them and good to work!
